# Generated by Django 3.2.3 on 2021-06-15 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='state',
            field=models.CharField(max_length=20),
        ),
    ]
