# Generated by Django 3.2.3 on 2021-06-16 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0005_auto_20210616_1237'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='employement',
            field=models.CharField(choices=[('employed', 'employed'), ('unemployed', 'unemployed'), ('selfemployed', 'selfemployed'), ('student', 'student')], default='student', max_length=20),
        ),
    ]
