# Generated by Django 3.2.3 on 2021-06-16 07:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0006_contact_employement'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='employement',
        ),
    ]
