# Generated by Django 3.2.3 on 2021-06-16 07:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0007_remove_contact_employement'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='bday',
        ),
    ]
