# Generated by Django 3.2.3 on 2021-06-16 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0008_remove_contact_bday'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='intro',
            field=models.CharField(max_length=200, null='true'),
            preserve_default='true',
        ),
        migrations.AddField(
            model_name='contact',
            name='qualification',
            field=models.CharField(max_length=50, null='true'),
            preserve_default='true',
        ),
    ]
